@startuml
skinparam defaultTextAlignment center
skinparam activityFontSize 16
skinparam conditionStyle diamond
|Pengguna|
start
:Membuka Aplikasi;
|Aplikasi|
:Menampilkan  Halaman Home;
|Pengguna|
:Menekan Tombol Tambah;
|Aplikasi|
:Menampilkan  Halaman Formulir Buat Pengumuman;
repeat
    |Pengguna|
    :Mengisi Data;
    :Menekan Tombol Post;
    |Aplikasi|
    :Validasi;
repeat while (data valid? Tidak) is (tidak)
->ya;
note left
  Melakukan pengecekan
  apakah judul dan deskripsi
  tidak kosong. Serta berkas tidak
  lebih dari 2 MB
end note
:Mengirim Data ke Web Service;
|Web Service|
:Menerima Data;
:Mengirim Respons;
|Aplikasi|
if(sukses?) then (ya)
    :Menampilkan Notifikasi Berhasil;
else(tidak)
    :Menampilkan Notifikasi Kesalahan;
endif
stop
@enduml
